local textplus = require("textplus")
local hudoverride = require("hudoverride")

local function calculateFinalScore()
    local totalscore = 0
    
    for i,v in pairs(SaveData.topscores) do
        totalscore = totalscore + v
    end

    if totalscore > 500000 then return "<color yellow>"..totalscore.."</color>" end

    return totalscore
end

local creditsArray = {
    "SMBX Credits",
	"",
	"",
	"",
	"Created by:",
	"Andrew Spinks",
	"('Redigit')",
	"",
	"",
	"",
	"Hacked By [LunaDll]:",
	"Kevsoft",
	"Rednaxela",
	"Kil",
	"Wohlstand",
	"",
	"",
	"",
	"Custom Sprites:",
	"Blue",
	"Iceman404",
	"LuigiFan",
	"NameUser",
	"Redigit",
	"Valtteri",
	"",
	"",
	"",
	"Special Thanks:",
	"4matsy",
	"AndyDark",
	"Bikcmp",
	"Blue",
	"Captain Obvious",
	"CaptainTrek",
	"Chase",
	"Coldwin",
	"CrystalMike",
	"DarkMatt",
	"FallingSnow",
	"Garro",
	"Knuckles96",
	"Kuribo",
	"Kyasarin",
	"Luminous",
	"m4sterbr0s",
	"NameUser",
	"Namyrr",
	"Qig",
	"Quill",
	"Red_Yoshi",
	"Spitfire",
	"Valtteri",
	"Vandarx",
	"Zephyr",
	"",
	"",
	"",
    "Castle of Oddities II Credits",
	"",
	"Lua:",
	"",
    "littleDialogue by MrDoubleA",
    "antizip.lua by Emral",
    "Frog Switch by Core",
    "FakeBlocks.lua by Sambo",
    "pauseMenu.lua by Marioman2007",
    "Gold Mushroom by FutureNyanCat",
    "Wario Movement Quintpack by \"Master\" of Disaster",
	"",
    "icantswim by cold soup",
    "NPC Tower by MrDoubleA",
    "Exclamation Mark Block by MrDoubleA",
    "Momentum Teleporters by Emral",
    "warioHealth by MrNameless",
	"",
	"Music:",
	"",
    "Originull Wasteland from Kirby and the Forgotten Land",
    "Haltmann Works Co. HQ from Kirby Planet Robobot",
    "Siege on Bowser's Castle from Paper Mario 64",
    "Petalburg from Paper Mario - The Thousand Year Door (Original)",
    "Cotton Island from Plok",
    "Kecleon Shop from Pokemon Mystery Dungeon - Red Rescue Team",
    "Windy Hill and Tornado (Windy Valley) from Sonic Adventure",
    "Vulkan Forge Zone from Sonic Robo Blast 2 - Mystic Realm Community Edition",
    "Sub Atomic from Strike the Earth! Shovel Knight Arranged",
    "Footlight Lane from Super Mario 3D World",
	"",
	"From Pizza Tower:",
	"Distasteful Anchovi [JC RE-EDIT]",
	"I Need A Noise",
	"It's Pizza Time!",
	"Receding Hairline Celebration Party",
	"The Death That I Deservioli",
	"World Wide Noise",
	"",
	"From Shovel Knight Dig:",
	"Spore Judgement",
	"Pest Friends",
	"Thermal Vent",
	"",
	"From Sonic Mania:",
	"Built to Rule",
	"Rogue's Gallery",
	"Skyway Octane",
	"Steel Cortex",
	"Wildstyle Pistolero",
	"",
	"From Sonic Superstars:",
	"Boss 2",
	"Bridge Island Zone 1",
	"Cyber Station Zone",
	"Lagoon City Zone 2",
	"Press Factory Zone 1",
	"Sand Sanctuary Zone",
	"Speed Jungle Zone (all acts)",
	"",
    "From Super Mario Bros. Wonder:",
    "Petal Isles - Castle Bowser",
    "Wonder Effect - Metal Mario",
	"",
    "From Wario Land 4:",
	"Hall of Hieroglyphs",
	"Hurry Up!",
	"Monsoon Jungle",
	"World Map",
	"",
	"Graphics:",
	"",
	"Custom Digital Tileset by AirShip",
	"Mario Maker 2 SMW Water Brick Tileset by Lithobraker",
	"SMW Chocolate Grass by Knuckles96",
	"SMW Mountain Tileset by AirShip & 8luestorm",
	"SMW Mystic Cavern Tileset by PixelPest",
	"",
	"Other:",
	"",
	"Various sound effects from Wario Land 4, taken from The Sounds Resource",
    "One sound effect from Mario Kart: Super Circuit is used for the havesomefun cheat",
    "A voice clip from Warioware Gold is used for the pizzatime cheat",
	"",
	"",
	"",
	"",
	"",
	"Level Design: ChromaNyan",
	"Anything not listed here: likely ChromaNyan",
	"(unless I missed a name, let me know if I did!)",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"\"Don't just sit there and waste your precious",
	"time. When you want to do something, do it right",
	"away. Do it when you can. It's the only way to",
	"live a life without regrets.\"",
	"- Sonic the Hedgehog 1 JP Box Art",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"<color pink>https://www.chromanyan.page/</color>",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"Thank you for playing!",
	"Final Score: "..calculateFinalScore(),
}

local credits = ""

local frame = 0

function onStart()
    hudoverride.visible.score = false
    changeWindowName("Emerged victorious from the")

    for i,v in pairs(creditsArray) do
        credits = credits..v.."\n"
    end
end

function onDraw()
    local sparse = textplus.parse(credits, {xscale = 2, yscale = 2, align = "center"})
    local slayout = textplus.layout(sparse)
    textplus.render({x = ((camera.width / 2) - slayout.width * 0.5), y = camera.height - frame, layout = slayout})

    if frame == 4499 then SFX.play(Misc.resolveFile("yahoo.wav")) end

    if frame >= 4500 then return end
    frame = frame + 1
end